name: hello-world
# 'on': push

jobs:
  my-job-1:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
  my-job-2:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: ls -ltr
  my-job-3:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: df -h